{{- $root := . -}}
{{ range $i, $e := until (int .Values.availability_domains) }}
{{-  $ad := $i | add 1 -}}
apiVersion: ocicore.oracle.com/v1alpha1
kind: Subnet
metadata:
  name: subnet-{{ $root.Values.region | lower }}-{{ $ad }}
  namespace: {{ $root.Values.namespace }}
spec:
  compartmentRef: {{ $root.Values.compartment }}
  vcnRef: {{ $root.Values.virtual_network }}
  availabilityDomain: {{ $root.Values.ad_prefix }}:{{ $root.Values.region | upper }}-AD-{{ $ad }}
  cidrBlock: 10.0.{{ $ad }}.0/24
  dnsLabel: {{ $root.Values.region | lower | replace "-" "" }}{{ $ad }}
  routetableRef: routetable1
  securityrulesetRefs:
  - securityruleset1
---
{{end}}
