apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.cloud.k8s.io
spec:
  group: cloud.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: networks
    kind: Network
