apiVersion: cloud.k8s.io/v1alpha1
kind: Security
metadata:
  name: worker
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    security: worker
spec:
  networkSelector:
    release: {{ .Release.Name }}
  ingress:
    - "0.0.0.0/0 tcp 22"
    - "0.0.0.0/0 tcp 10250"
