# // Instance A compute host. The image used to launch the instance determines its operating system and other
# // software. The shape specified during the launch process determines the number of CPUs and memory
# // allocated to the instance. For more information, see
# // Overview of the Compute Service (https://docs.us-phoenix-1.oraclecloud.com/Content/Compute/Concepts/computeoverview.htm).
# // To use any of the API operations, you must be authorized in an IAM policy. If you're not authorized,
# // talk to an administrator. If you're an administrator who needs to write policies to give users access, see
# // Getting Started with Policies (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/policygetstarted.htm).

apiVersion: ocicore.oracle.com/v1alpha1
kind: Instance
metadata:
  name: example-instance1
spec:
  compartmentRef: default
  availabilityDomain: yhkn:PHX-AD-1
  subnetRef: example-subnet1
  shape: VM.Standard2.2
  image: Canonical-Ubuntu-18.04-2018.10.16-0
  metadata:
    #ssh_authorized_keys: <insert ssh pub key here>
    user_data: IyEvYmluL2Jhc2gKCmFwdC1nZXQgdXBkYXRlCmFwdC1nZXQgaW5zdGFsbCAteSBuZ2lueC1saWdodAppcHRhYmxlcyAtRgo=
