# // Listener configuration for the front-end of a Load Balancer
# // For more information, see https://docs.us-phoenix-1.oraclecloud.com/Content/Balance/Tasks/managinglisteners.htm

apiVersion: ocilb.oracle.com/v1alpha1
kind: Listener
metadata:
  name: example-listener
spec:
  loadBalancerRef: example-lb
  certificateRef: example-cert
  port: 443
  # HTTP does HTTPS when cert is used
  protocol: HTTP
  defaultBackendSetName: example-backendset
  idleTimeout: 3
