# // LoadBalancer The properties that define a load balancer. For more information, see
# // Managing a Load Balancer (https://docs.us-phoenix-1.oraclecloud.com/Content/Balance/Tasks/managingloadbalancer.htm).
# // To use any of the API operations, you must be authorized in an IAM policy. If you're not authorized,
# // talk to an administrator. If you're an administrator who needs to write policies to give users access, see
# // Getting Started with Policies (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/policygetstarted.htm).
# // For information about endpoints and signing API requests, see
# // About the API (https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/usingapi.htm). For information about available SDKs and tools, see
# // SDKS and Other Tools (https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdks.htm).

apiVersion: ocilb.oracle.com/v1alpha1
kind: LoadBalancer
metadata:
  name: example-lb
spec:
  compartmentRef: default 
  subnetRefs:
    - example-subnet1
    - example-subnet2
  isPrivate: false
  shapeName: 100Mbps
