# // RouteTable A collection of `RouteRule` objects, which are used to route packets
# // based on destination IP to a particular network entity. For more information, see
# // Overview of the Networking Service (https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Concepts/overview.htm).
# // To use any of the API operations, you must be authorized in an IAM policy. If you're not authorized,
# // talk to an administrator. If you're an administrator who needs to write policies to give users access, see
# // Getting Started with Policies (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/policygetstarted.htm).

apiVersion: ocicore.oracle.com/v1alpha1
kind: RouteTable
metadata:
  name: example-rt
spec:
  compartmentRef: default
  vcnRef: example
  routeRules:
  - cidrBlock: 0.0.0.0/0
    networkEntityId: example-ig
