# // SecurityList A set of virtual firewall rules for your VCN. Security lists are configured at the subnet
# // level, but the rules are applied to the ingress and egress traffic for the individual instances
# // in the subnet. The rules can be stateful or stateless. For more information, see
# // Security Lists (https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Concepts/securitylists.htm).
# // **Important:** Oracle Cloud Infrastructure Compute service images automatically include firewall rules (for example,
# // Linux iptables, Windows firewall). If there are issues with some type of access to an instance,
# // make sure both the security lists associated with the instance's subnet and the instance's
# // firewall rules are set correctly.
# // To use any of the API operations, you must be authorized in an IAM policy. If you're not authorized,
# // talk to an administrator. If you're an administrator who needs to write policies to give users access, see
# // Getting Started with Policies (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/policygetstarted.htm).

apiVersion: ocicore.oracle.com/v1alpha1
kind: SecurityRuleSet
metadata:
  name: example-secrule
spec:
  compartmentRef: default
  vcnRef: example
  egressSecurityRules:
  - destination: 0.0.0.0/0
    protocol: all
  ingressSecurityRules:
  - source: 0.0.0.0/0
    protocol: '6'
    tcpOptions:
      destinationPortRange:
        min: 22
        max: 22
  - source: 0.0.0.0/0
    protocol: '6'
    tcpOptions:
      destinationPortRange:
        min: 80
        max: 80
  - source: 0.0.0.0/0
    protocol: '6'
    tcpOptions:
      destinationPortRange:
        min: 443
        max: 443
