# // Volume A detachable block volume device that allows you to dynamically expand
# // the storage capacity of an instance. For more information, see
# // Overview of Cloud Volume Storage (https://docs.us-phoenix-1.oraclecloud.com/Content/Block/Concepts/overview.htm).
# // To use any of the API operations, you must be authorized in an IAM policy. If you're not authorized,
# // talk to an administrator. If you're an administrator who needs to write policies to give users access, see
# // Getting Started with Policies (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/policygetstarted.htm).

apiVersion: ocicore.oracle.com/v1alpha1
kind: VolumeBackup
metadata:
  name: example-vol1-backup
spec:
  volumeRef: example-vol1
  displayName: example-vol1-backup
  type: FULL
