---
apiVersion: oci.oracle.com/v1
kind: Instance
metadata:
  name: {{ .Values.compartment }}.routetable.{{ .Chart.Name }}
spec:
  displayName: {{ .Chart.Name }}
  compartmentRef: {{ .Values.compartment }}
  subnetRef: {{ .Values.compartment }}.subnet.{{ .Chart.Name }}
  availabilityDomain: yhkn:PHX-AD-1
  shape: {{ default "VM.Standard1.1" .Values.shape }}
  image: {{ default "Canonical-Ubuntu-16.04-2017.08.22-0" .Values.image }}
  metadata:
    ssh_authorized_keys: {{ .Values.sshkey }}
    user_data: {{ .Files.Get "scripts/user_data.sh" | b64enc }}
