apiVersion: oci.oracle.com/v1
kind: RouteTable
metadata:
  name: {{ .Values.compartment }}.routetable.{{ .Chart.Name }}
spec:
  displayName: {{ .Chart.Name }}
  compartmentRef: {{ .Values.compartment }}
  virtualnetworkRef: {{ .Values.compartment }}.virtualnetwork.{{ .Chart.Name }}
  routeRules:
  - cidrBlock: 0.0.0.0/0
    networkEntityId:  {{ .Values.compartment }}.internetgateway.{{ .Chart.Name }}
