apiVersion: cloud.k8s.io/v1alpha1
kind: Compute
metadata:
  name: test
  namespace: default
  labels:
    app: test
    version: v0.9
  annotations:
    oci.oracle.com/instance.image: Oracle-Linux-7.5-2018.07.20-0
    oci.oracle.com/instance.shape: VM.Standard1.2
spec:
  network: test
  securitySelector:
    type: web
  replicas: 3
  template:
    osType: oracle-linux
    osVersion: "7.5"
    resources:
      limits:
        cpu: 2
        memory: 2G
      requests:
        cpu: 1
        memory: 1G
    sshKeys: ["change-me"]
    userData:
      shellscript: |
        #!/bin/bash -x
        yum -y install httpd
        systemctl start httpd ; systemctl enable httpd
        systemctl stop firewalld ; systemctl disable firewalld
        printf "\nhello world\n" > /var/www/html/index.html
